version: 2.1

# reusable docker image
docker-image: &docker-image
  docker:
      - image: circleci/node:13.8.0

jobs:
  build:
    <<: *docker-image
    steps:
      - checkout
      - run: npm i
      - save_cache:
          paths:
            - /src/node_modules
          key: "npm-packages"
      - run: npm run build

workflows:
  my_workflow:
    jobs:
      - build